language: generic
sudo: required
services:
  - docker

before_install:
  - ls
  - cd client && pwd && ls
  - docker build -t awwumbrage/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true awwumbrage/react-test npm test

after_success:
  - docker build -t awwumbrage/multi-client ./client
  - docker build -t awwumbrage/multi-nginx ./nginx
  - docker build -t awwumbrage/multi-server ./server
  - docker build -t awwumbrage/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push awwumbrage/multi-client
  - docker push awwumbrage/multi-nginx
  - docker push awwumbrage/multi-server
  - docker push awwumbrage/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-564567100372"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
