language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aww-umbrage/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aww-umbrage/react-test npm test

after_success:
  - docker build -t aww-umbrage/multi-client ./client
  - docker build -t aww-umbrage/multi-nginx ./nginx
  - docker build -t aww-umbrage/multi-server ./server
  - docker build -t aww-umbrage/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push aww-umbrage/multi-client
  - docker push aww-umbrage/multi-nginx
  - docker push aww-umbrage/multi-server
  - docker push aww-umbrage/multi-worker
